version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch-minirag
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kibana-minirag
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-minirag
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull-model:
    image: ollama/ollama:latest
    container_name: ollama-pull-model
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: >
      -c "sleep 10;
      echo 'Checking for llava:7b...';
      ollama serve &
      sleep 5;
      ollama pull llava:7b;
      echo 'Model ready';"
    depends_on:
      - ollama

  fastapi-next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_next_app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - db_data:/.db
      - local_models:/.local_models
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - ollama-pull-model

volumes:
  es_data:
  ollama_data:
  db_data:
  local_models:
